// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaKl93QTjgrNObn9sRqjX_bRE9sfRyAc8',
    appId: '1:320896577951:web:699de1eb922284bcaa4daa',
    messagingSenderId: '320896577951',
    projectId: 'health-tracker-6e37d',
    authDomain: 'health-tracker-6e37d.firebaseapp.com',
    storageBucket: 'health-tracker-6e37d.firebasestorage.app',
    measurementId: 'G-68MKDMMK2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZCjL3Bn5ooCY24cufKwlrWUKvpxL1lfU',
    appId: '1:320896577951:android:0c75886cc249117eaa4daa',
    messagingSenderId: '320896577951',
    projectId: 'health-tracker-6e37d',
    storageBucket: 'health-tracker-6e37d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpstkUZi2wsCQjHgvP0YshtIWVJOidRhU',
    appId: '1:320896577951:ios:702f4b9465a82075aa4daa',
    messagingSenderId: '320896577951',
    projectId: 'health-tracker-6e37d',
    storageBucket: 'health-tracker-6e37d.firebasestorage.app',
    iosBundleId: 'com.example.mvc1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpstkUZi2wsCQjHgvP0YshtIWVJOidRhU',
    appId: '1:320896577951:ios:702f4b9465a82075aa4daa',
    messagingSenderId: '320896577951',
    projectId: 'health-tracker-6e37d',
    storageBucket: 'health-tracker-6e37d.firebasestorage.app',
    iosBundleId: 'com.example.mvc1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaKl93QTjgrNObn9sRqjX_bRE9sfRyAc8',
    appId: '1:320896577951:web:2b401b822bf3165faa4daa',
    messagingSenderId: '320896577951',
    projectId: 'health-tracker-6e37d',
    authDomain: 'health-tracker-6e37d.firebaseapp.com',
    storageBucket: 'health-tracker-6e37d.firebasestorage.app',
    measurementId: 'G-D4ZH8V0VDN',
  );
}
